runtime: nodejs12
instance_class: F4

handlers:
- url: .*
  secure: always
  script: auto

includes:
  - secret_env_vars.yaml

env_variables:
  ACTION_HUB_LABEL: 'Google AutoMl Action Hub'
  PORT: '8080'
  ACTION_DEBUG: '0'
  ACTION_WHITELIST: 'google_automl_table'

automatic_scaling:
  max_instances: 3
